### ISSUE TITLE
[SERVER-CRASH] 1.21.1

### ISSUE THREAD

**Issue by Dinocraft1515YT** [BigBull-H3RO/Vibranium#1]
### Mod Name

Vibranium and EvilCraft

### Minecraft version

1.21.1

### Describe the bug

Just a server crash on start

### Steps to reproduce

1. Install NeoForge 1.21.1 as a server on your PC
2. Install the mod for the latest version (1.21.1) with this modpack I made: https://drive.google.com/file/d/1oUsEMtHHWoAylPFJkzm2vHLXks_PdYMM/view?usp=sharing
3. Execute the server
4. Server crash

### Logs

https://gist.github.com/Dinocraft1515YT/5cd2f311998d47bcb3354b891c942534 and Crash report: https://gist.github.com/Dinocraft1515YT/2436e6f97418dd99a5e381a3bc64283b

### Additional context

https://github.com/CyclopsMC/EvilCraft/issues/1063#event-14366004567

**Comment by BigBull-H3RO** [comment]
Thanks for reporting! I've identified the issue, and the fix will be included in the next update. In the meantime, please use version 0.1 or 0.2 of the mod, as these should not cause a server crash.
